//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Logsheet
    {
        public int Logsheet_ID { get; set; }
        public Nullable<System.DateTime> Day_Of_The_Week { get; set; }
        public string Time_In { get; set; }
        public string Lunch_Out { get; set; }
        public string Lunch_In { get; set; }
        public string Time_Out { get; set; }
        public int Employee_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
