//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Role()
        {
            this.Access_Level = new HashSet<Access_Level>();
        }
    
        public int User_Role_Id { get; set; }
        public bool Admin_Role { get; set; }
        public bool User_And_Access_Level_Role { get; set; }
        public bool Employee_Role { get; set; }
        public bool Client_Order_Role { get; set; }
        public bool Supplier_Order_Role { get; set; }
        public bool Product_Role { get; set; }
        public bool Sale_Role { get; set; }
        public bool Vehicle_Role { get; set; }
        public bool Reports_Role { get; set; }
        public bool Client_Role { get; set; }
        public bool Website_Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Access_Level> Access_Level { get; set; }
    }
}
