//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Client_Purchase_Order_Line = new HashSet<Client_Purchase_Order_Line>();
            this.Sales_Order_line = new HashSet<Sales_Order_line>();
            this.Supplier_Order_Line = new HashSet<Supplier_Order_Line>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Description { get; set; }
        public Nullable<int> Available_Quantity { get; set; }
        public Nullable<int> Product_Type_ID { get; set; }
        public Nullable<int> Product_Brand_ID { get; set; }
        public Nullable<int> Ply_ID { get; set; }
        public Nullable<int> Pack_Size_ID { get; set; }
        public Nullable<int> Sheet_ID { get; set; }
        public Nullable<int> Length_ID { get; set; }
        public Nullable<int> Width_ID { get; set; }
        public string Image { get; set; }
        public string Review { get; set; }
        public Nullable<decimal> Sales_Price { get; set; }
        public Nullable<decimal> Order_Price { get; set; }
        public Nullable<bool> Is_Advertised { get; set; }
        public string PR_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Purchase_Order_Line> Client_Purchase_Order_Line { get; set; }
        public virtual Pack_Size Pack_Size { get; set; }
        public virtual pLength pLength { get; set; }
        public virtual Ply Ply { get; set; }
        public virtual Product_Type Product_Type { get; set; }
        public virtual Product_Brand Product_Brand { get; set; }
        public virtual Sheet Sheet { get; set; }
        public virtual Width Width { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order_line> Sales_Order_line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Order_Line> Supplier_Order_Line { get; set; }
    }
}
