//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SPEntities : DbContext
    {
        public SPEntities()
            : base("name=SPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access_Level> Access_Level { get; set; }
        public virtual DbSet<Active_User> Active_User { get; set; }
        public virtual DbSet<Audit_Create_Delete> Audit_Create_Delete { get; set; }
        public virtual DbSet<Audit_Log> Audit_Log { get; set; }
        public virtual DbSet<Audit_Update> Audit_Update { get; set; }
        public virtual DbSet<Backorder_Line> Backorder_Line { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Client_Account_Status> Client_Account_Status { get; set; }
        public virtual DbSet<Client_Purchase_Order> Client_Purchase_Order { get; set; }
        public virtual DbSet<Client_Purchase_Order_Line> Client_Purchase_Order_Line { get; set; }
        public virtual DbSet<Company_Information> Company_Information { get; set; }
        public virtual DbSet<Credit_Approval> Credit_Approval { get; set; }
        public virtual DbSet<Credit_Return> Credit_Return { get; set; }
        public virtual DbSet<Credit_Return_Line> Credit_Return_Line { get; set; }
        public virtual DbSet<Credit_Status> Credit_Status { get; set; }
        public virtual DbSet<Dispatch> Dispatches { get; set; }
        public virtual DbSet<Dispatch_Type> Dispatch_Type { get; set; }
        public virtual DbSet<Email_Notice_Template> Email_Notice_Template { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Logsheet> Employee_Logsheet { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<Pack_Size> Pack_Size { get; set; }
        public virtual DbSet<Payment_Term> Payment_Term { get; set; }
        public virtual DbSet<pLength> pLengths { get; set; }
        public virtual DbSet<Ply> Plies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Brand> Product_Brand { get; set; }
        public virtual DbSet<Product_Type> Product_Type { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Purchase_Order_Status> Purchase_Order_Status { get; set; }
        public virtual DbSet<Reason_For_Return> Reason_For_Return { get; set; }
        public virtual DbSet<Refund_Line> Refund_Line { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Sale_Refund> Sale_Refund { get; set; }
        public virtual DbSet<Sales_Order_line> Sales_Order_line { get; set; }
        public virtual DbSet<Sheet> Sheets { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supplier_Backorder> Supplier_Backorder { get; set; }
        public virtual DbSet<Supplier_Order> Supplier_Order { get; set; }
        public virtual DbSet<Supplier_Order_Line> Supplier_Order_Line { get; set; }
        public virtual DbSet<Supplier_Order_Status> Supplier_Order_Status { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Vehicle_Status> Vehicle_Status { get; set; }
        public virtual DbSet<Width> Widths { get; set; }
    
        public virtual ObjectResult<Get_Credit_Return_Line_Result> Get_Credit_Return_Line(Nullable<int> crnum)
        {
            var crnumParameter = crnum.HasValue ?
                new ObjectParameter("crnum", crnum) :
                new ObjectParameter("crnum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Credit_Return_Line_Result>("Get_Credit_Return_Line", crnumParameter);
        }
    
        public virtual ObjectResult<GetAddress_Result> GetAddress(Nullable<int> cid, Nullable<int> pid)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAddress_Result>("GetAddress", cidParameter, pidParameter);
        }
    
        public virtual ObjectResult<GetBOL_Result> GetBOL(Nullable<int> soid)
        {
            var soidParameter = soid.HasValue ?
                new ObjectParameter("soid", soid) :
                new ObjectParameter("soid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBOL_Result>("GetBOL", soidParameter);
        }
    
        public virtual ObjectResult<string> GetDeliveryVehicle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetDeliveryVehicle");
        }
    
        public virtual ObjectResult<string> GetDriver()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetDriver");
        }
    
        public virtual ObjectResult<GetIsAdvert_Result> GetIsAdvert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIsAdvert_Result>("GetIsAdvert");
        }
    
        public virtual ObjectResult<GetOrderToConfirm_Result> GetOrderToConfirm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderToConfirm_Result>("GetOrderToConfirm");
        }
    
        public virtual ObjectResult<GetOrderToLoad_Result> GetOrderToLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderToLoad_Result>("GetOrderToLoad");
        }
    
        public virtual ObjectResult<Getpoduct_Result> Getpoduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getpoduct_Result>("Getpoduct");
        }
    
        public virtual ObjectResult<GetPOL_Result> GetPOL(Nullable<int> poid)
        {
            var poidParameter = poid.HasValue ?
                new ObjectParameter("poid", poid) :
                new ObjectParameter("poid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPOL_Result>("GetPOL", poidParameter);
        }
    
        public virtual ObjectResult<GetSOL_Result> GetSOL(Nullable<int> soid)
        {
            var soidParameter = soid.HasValue ?
                new ObjectParameter("soid", soid) :
                new ObjectParameter("soid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSOL_Result>("GetSOL", soidParameter);
        }
    
        public virtual ObjectResult<GetTotalQty_Result> GetTotalQty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalQty_Result>("GetTotalQty");
        }
    
        public virtual ObjectResult<Load_Client_Result> Load_Client()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_Client_Result>("Load_Client");
        }
    
        public virtual ObjectResult<Load_Credit_Return_Result> Load_Credit_Return()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_Credit_Return_Result>("Load_Credit_Return");
        }
    
        public virtual ObjectResult<Load_Purcase_Order_Line_Result> Load_Purcase_Order_Line()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_Purcase_Order_Line_Result>("Load_Purcase_Order_Line");
        }
    
        public virtual ObjectResult<Load_Purchase_Order_Result> Load_Purchase_Order()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_Purchase_Order_Result>("Load_Purchase_Order");
        }
    
        public virtual ObjectResult<Load_Purchase_Order_1_Result> Load_Purchase_Order_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_Purchase_Order_1_Result>("Load_Purchase_Order_1");
        }
    
        public virtual ObjectResult<Load_Supplier_Order_Result> Load_Supplier_Order()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_Supplier_Order_Result>("Load_Supplier_Order");
        }
    }
}
