//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Create_Delete
    {
        public int Audit_Create_Delete_Id { get; set; }
        public Nullable<int> PK_Row_Effected { get; set; }
        public Nullable<bool> Created { get; set; }
        public string Value { get; set; }
        public Nullable<int> Audit_Log_Id { get; set; }
    
        public virtual Audit_Log Audit_Log { get; set; }
    }
}
