//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_Information()
        {
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public string VAT_Number { get; set; }
        public decimal VAT_Percentage { get; set; }
        public string Registration_Number { get; set; }
        public string Email_Address { get; set; }
        public string Telephone_Number { get; set; }
        public string Supplier_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
